export const SAVE_USER = 'SAVE_USER';
export const USER_DB_CHECKER = 'USER_DB_CHECKER';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';
export const SET_USER_POINTS = 'SET_USER_POINTS';
